version: '3.1'
services:

  frontend:
    build: ./frontend
    ports:
      - 80:80

  backend:
     build: ./lib_catalog
     ports:
       - 8000:8000
     depends_on:
       - database 

  database:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes: 
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django -d django"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

